---
proseWrap: always
jsonRecursiveSort: true # prettier-plugin-sort-json
tabWidth: 2
useTabs: false
overrides:
  - files:
      - "*.md"
    options:
      # compatibility with markdownlint
      proseWrap: always
      printWidth: 80
  - files:
      - "*.yaml"
      - "*.yml"
    options:
      # compatibility with yamllint
      proseWrap: preserve
# https://github.com/prettier/prettier/issues/15141
# plugins:
#   - prettier-plugin-sort-json
