---
site_name: mk tool documentation
site_url: https://mk.readthedocs.io/
repo_url: https://github.com/pycontribs/mk
edit_uri: blob/main/docs/
copyright: Copyright © 2021-2023 Sorin Sbarnea
docs_dir: docs
strict: true

extra_css:
  - stylesheets/extra.css

theme:
  name: "material"
  custom_dir: docs/.overrides
  logo: images/logo.svg
  favicon: images/favicon.ico
  features:
    - announce.dismiss
    - content.code.copy
    - content.action.edit
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - toc.integrate
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
    - media: "(prefers-color-scheme: light)"
      primary: green
      accent: green
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: green
      accent: green
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mk/
      name: PyPI
    - icon: fontawesome/solid/scroll
      link: https://github.com/pycontribs/mk/releases
      name: Releases
    - icon: fontawesome/solid/comments
      link: https://github.com/pycontribs/mk/discussions
      name: Discussions
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pycontribs/mk
      name: GitHub

plugins:
  - autorefs
  - markdown-exec
  - search
  - social
  - tags
  # https://github.com/manuzhang/mkdocs-htmlproofer-plugin
  - htmlproofer

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 2
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
