---
# See https://github.com/ansible/team-devtools/blob/main/.github/workflows/push.yml
name: push
on:
  push:
    branches:
      - main
      - releases/**
      - stable/**

jobs:
  ack:
    uses: ansible/team-devtools/.github/workflows/push.yml@ee2bbd460cd939f3f039d20c263263d73c257bd1 # main
