---
# See https://github.com/ansible/team-devtools/blob/main/.github/workflows/push.yml
name: push
on:
  push:
    branches:
      - main
      - releases/**
      - stable/**

jobs:
  ack:
    uses: ansible/team-devtools/.github/workflows/push.yml@f13b90b8baf842eef92fa0561017404230a7c1df # main
