---
# See https://github.com/ansible/team-devtools/blob/main/.github/workflows/push.yml
name: push
on:
  push:
    branches:
      - main
      - releases/**
      - stable/**

jobs:
  ack:
    uses: ansible/team-devtools/.github/workflows/push.yml@6a13751f3d8da7d939d091371efdc00a668ed578 # main
